namespace: opentelemetry-demo
kubernetesClusterDomain: cluster.local

serviceAccount:
  name: opentelemetry-demo
  version: ">=1.32.0-0"
  partOf: opentelemetry-demo

opentelemetryDemoImageprovider:
  imageprovider:
    env:
      imageProviderPort: "8081"
      otelCollectorHost: $(OTEL_COLLECTOR_NAME)
      otelCollectorName: opentelemetry-demo-otelcol
      otelCollectorPortGrpc: "4317"
      otelExporterOtlpMetricsTemporalityPreference: cumulative
      otelResourceAttributes: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=2.1.3
    image:
      repository: ghcr.io/open-telemetry/demo
      tag: 2.1.3-image-provider
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 50Mi
  ports:
  - name: tcp-service
    port: 8081
    targetPort: 8081
  replicas: 1
  revisionHistoryLimit: 10
  type: ClusterIP
