apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "cart.fullname" . }}
  labels:
    app.kubernetes.io/component: cartservice
    app.kubernetes.io/part-of: opentelemetry-demo
    opentelemetry.io/name: opentelemetry-demo-cartservice
  {{- include "cart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.opentelemetryDemoCartservice.replicas }}
  revisionHistoryLimit: {{ .Values.opentelemetryDemoCartservice.revisionHistoryLimit
    }}
  selector:
    matchLabels:
      opentelemetry.io/name: {{ .Values.namespace }}-{{ include "cart.fullname" . }}
    {{- include "cart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: cartservice
        app.kubernetes.io/instance: opentelemetry-demo
        app.kubernetes.io/name: {{ .Values.namespace }}-{{ include "cart.fullname" . }}
        opentelemetry.io/name: {{ .Values.namespace }}-{{ include "cart.fullname" . }}
      {{- include "cart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/component']
        - name: OTEL_COLLECTOR_NAME
          value: {{ quote .Values.opentelemetryDemoCartservice.cartservice.env.otelCollectorName
            }}
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: {{ quote .Values.opentelemetryDemoCartservice.cartservice.env.otelExporterOtlpMetricsTemporalityPreference
            }}
        - name: CART_PORT
          value: {{ quote .Values.opentelemetryDemoCartservice.cartservice.env.cartServicePort
            }}
        - name: ASPNETCORE_URLS
          value: {{ quote .Values.opentelemetryDemoCartservice.cartservice.env.aspnetcoreUrls
            }}
        - name: VALKEY_ADDR
          value: {{ quote .Values.opentelemetryDemoCartservice.cartservice.env.valkeyAddr
            }}
        - name: FLAGD_HOST
          value: {{ quote .Values.opentelemetryDemoCartservice.cartservice.env.flagdHost
            }}
        - name: FLAGD_PORT
          value: {{ quote .Values.opentelemetryDemoCartservice.cartservice.env.flagdPort
            }}
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ quote .Values.opentelemetryDemoCartservice.cartservice.env.otelExporterOtlpEndpoint
            }}
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: {{ quote .Values.opentelemetryDemoCartservice.cartservice.env.otelResourceAttributes
            }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: '{{ .Values.opentelemetryDemoCartservice.cartservice.image.repository }}:{{
          .Values.opentelemetryDemoCartservice.cartservice.image.tag | default .Chart.AppVersion
          }}'
        imagePullPolicy: {{ .Values.opentelemetryDemoCartservice.cartservice.imagePullPolicy
          }}
        name: cartservice
        ports:
        - containerPort: 8080
          name: service
        resources: {{- toYaml .Values.opentelemetryDemoCartservice.cartservice.resources
          | nindent 10 }}
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z -v -w30 opentelemetry-demo-valkey 6379; do echo waiting for valkey;
          sleep 2; done;
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: '{{ .Values.opentelemetryDemoCartservice.waitForValkey.image.repository }}:{{
          .Values.opentelemetryDemoCartservice.waitForValkey.image.tag | default .Chart.AppVersion
          }}'
        name: wait-for-valkey
        resources: {}
      serviceAccountName: {{ .Values.serviceAccount.name }}
