apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontendproxy.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "frontendproxy.labels" . | nindent 4 }}
data:
  envoy.yaml: |
    static_resources:
      listeners:
        - address:
            socket_address:
              address: "0.0.0.0"
              port_value: 8080
          filter_chains:
            - filters:
                - name: "envoy.filters.network.http_connection_manager"
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: "ingress_http"
                    route_config:
                      name: "local_route"
                      virtual_hosts:
                        - name: "frontend"
                          domains: ["*"]
                          routes:
                            - match:
                                prefix: "/"
                              route:
                                cluster: "frontend"
                    http_filters:
                      - name: "envoy.filters.http.router"
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
        - name: "frontend"
          type: STRICT_DNS
          load_assignment:
            cluster_name: "frontend"
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: "{{ .Values.opentelemetryDemoFrontendproxy.frontendproxy.env.frontendHost }}"
                          port_value: {{ .Values.opentelemetryDemoFrontendproxy.frontendproxy.env.frontendPort }}
    admin:
      address:
        socket_address:
          address: "0.0.0.0"
          port_value: {{ .Values.opentelemetryDemoFrontendproxy.frontendproxy.env.envoyAdminPort }}