apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namespace }}-{{ include "flagd.fullname" . }}
  labels:
    app.kubernetes.io/component: flagd
    app.kubernetes.io/part-of: opentelemetry-demo
    opentelemetry.io/name: {{ .Values.namespace }}-{{ include "flagd.fullname" . }}
  {{- include "flagd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.opentelemetryDemoFlagd.type }}
  selector:
    opentelemetry.io/name: {{ .Values.namespace }}-{{ include "flagd.fullname" . }}
    {{- include "flagd.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.opentelemetryDemoFlagd.ports | toYaml | nindent 2 }}
