apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "email.fullname" . }}
  labels:
    app.kubernetes.io/component: emailservice
    app.kubernetes.io/part-of: opentelemetry-demo
    opentelemetry.io/name: {{ .Values.namespace }}-{{ include "email.fullname" . }}
  {{- include "email.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.opentelemetryDemoEmailservice.replicas }}
  revisionHistoryLimit: {{ .Values.opentelemetryDemoEmailservice.revisionHistoryLimit
    }}
  selector:
    matchLabels:
      opentelemetry.io/name: {{ .Values.namespace }}-{{ include "email.fullname" . }}
    {{- include "email.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: emailservice
        app.kubernetes.io/instance: opentelemetry-demo
        app.kubernetes.io/name: {{ .Values.namespace }}-{{ include "email.fullname" . }}
        opentelemetry.io/name: {{ .Values.namespace }}-{{ include "email.fullname" . }}
      {{- include "email.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/component']
        - name: OTEL_COLLECTOR_NAME
          value: {{ quote .Values.opentelemetryDemoEmailservice.emailservice.env.otelCollectorName
            }}
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: {{ quote .Values.opentelemetryDemoEmailservice.emailservice.env.otelExporterOtlpMetricsTemporalityPreference
            }}
        - name: EMAIL_PORT
          value: {{ quote .Values.opentelemetryDemoEmailservice.emailservice.env.emailServicePort
            }}
        - name: APP_ENV
          value: {{ quote .Values.opentelemetryDemoEmailservice.emailservice.env.appEnv
            }}
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: {{ quote .Values.opentelemetryDemoEmailservice.emailservice.env.otelExporterOtlpTracesEndpoint
            }}
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: {{ quote .Values.opentelemetryDemoEmailservice.emailservice.env.otelResourceAttributes
            }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: '{{ .Values.opentelemetryDemoEmailservice.emailservice.image.repository }}:{{
          .Values.opentelemetryDemoEmailservice.emailservice.image.tag | default .Chart.AppVersion
          }}'
        imagePullPolicy: {{ .Values.opentelemetryDemoEmailservice.emailservice.imagePullPolicy
          }}
        name: emailservice
        ports:
        - containerPort: 8080
          name: service
        resources: {{- toYaml .Values.opentelemetryDemoEmailservice.emailservice.resources
          | nindent 10 }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
