apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "fraud-detection.fullname" . }}
  labels:
    app.kubernetes.io/component: fraud-detectionservice
    app.kubernetes.io/part-of: opentelemetry-demo
    opentelemetry.io/name: {{ .Values.namespace }}-{{ include "fraud-detection.fullname" . }}
  {{- include "fraud-detection.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.opentelemetryDemoFrauddetectionservice.replicas }}
  revisionHistoryLimit: {{ .Values.opentelemetryDemoFrauddetectionservice.revisionHistoryLimit }}
  selector:
    matchLabels:
      opentelemetry.io/name: {{ .Values.namespace }}-{{ include "fraud-detection.fullname" . }}
      {{- include "fraud-detection.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: fraud-detectionservice
        app.kubernetes.io/instance: opentelemetry-demo
        app.kubernetes.io/name: {{ .Values.namespace }}-{{ include "fraud-detection.fullname" . }}
        opentelemetry.io/name: {{ .Values.namespace }}-{{ include "fraud-detection.fullname" . }}
        {{- include "fraud-detection.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: OTEL_SERVICE_NAME
          value: {{ quote .Values.opentelemetryDemoFrauddetectionservice.fraudDetectionservice.env.otelServiceName }}
        - name: OTEL_COLLECTOR_NAME
          value: {{ quote .Values.opentelemetryDemoFrauddetectionservice.fraudDetectionservice.env.otelCollectorName }}
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: {{ quote .Values.opentelemetryDemoFrauddetectionservice.fraudDetectionservice.env.otelExporterOtlpMetricsTemporalityPreference }}
        - name: KAFKA_ADDR
          value: {{ quote .Values.opentelemetryDemoFrauddetectionservice.fraudDetectionservice.env.kafkaServiceAddr }}
        - name: FLAGD_HOST
          value: {{ quote .Values.opentelemetryDemoFrauddetectionservice.fraudDetectionservice.env.flagdHost }}
        - name: FLAGD_PORT
          value: {{ quote .Values.opentelemetryDemoFrauddetectionservice.fraudDetectionservice.env.flagdPort }}
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ quote .Values.opentelemetryDemoFrauddetectionservice.fraudDetectionservice.env.otelExporterOtlpEndpoint }}
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: {{ quote .Values.opentelemetryDemoFrauddetectionservice.fraudDetectionservice.env.otelResourceAttributes }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: '{{ .Values.opentelemetryDemoFrauddetectionservice.fraudDetectionservice.image.repository }}:{{ .Values.opentelemetryDemoFrauddetectionservice.fraudDetectionservice.image.tag | default .Chart.AppVersion }}'
        imagePullPolicy: {{ .Values.opentelemetryDemoFrauddetectionservice.fraudDetectionservice.imagePullPolicy }}
        name: fraud-detectionservice
        resources: {{- toYaml .Values.opentelemetryDemoFrauddetectionservice.fraudDetectionservice.resources | nindent 10 }}
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z -v -w30 opentelemetry-demo-kafka 9092; do echo waiting for kafka; sleep 2; done;
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: '{{ .Values.opentelemetryDemoFrauddetectionservice.waitForKafka.image.repository }}:{{ .Values.opentelemetryDemoFrauddetectionservice.waitForKafka.image.tag | default .Chart.AppVersion }}'
        name: wait-for-kafka
        resources: {}
      serviceAccountName: {{ .Values.serviceAccount.name }}
