apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "recommendation.fullname" . }}
  labels:
    app.kubernetes.io/component: recommendationservice
    app.kubernetes.io/part-of: opentelemetry-demo
    opentelemetry.io/name: {{ .Values.namespace }}-{{ include "recommendation.fullname" . }}
  {{- include "recommendation.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.opentelemetryDemoRecommendationservice.replicas }}
  revisionHistoryLimit: {{ .Values.opentelemetryDemoRecommendationservice.revisionHistoryLimit
    }}
  selector:
    matchLabels:
      opentelemetry.io/name: {{ .Values.namespace }}-{{ include "recommendation.fullname" . }}
    {{- include "recommendation.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: recommendationservice
        app.kubernetes.io/instance: opentelemetry-demo
        app.kubernetes.io/name: {{ .Values.namespace }}-{{ include "recommendation.fullname" . }}
        opentelemetry.io/name: {{ .Values.namespace }}-{{ include "recommendation.fullname" . }}
      {{- include "recommendation.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/component']
        - name: OTEL_COLLECTOR_NAME
          value: {{ quote .Values.opentelemetryDemoRecommendationservice.recommendationservice.env.otelCollectorName
            }}
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: {{ quote .Values.opentelemetryDemoRecommendationservice.recommendationservice.env.otelExporterOtlpMetricsTemporalityPreference
            }}
        - name: RECOMMENDATION_PORT
          value: {{ quote .Values.opentelemetryDemoRecommendationservice.recommendationservice.env.recommendationServicePort
            }}
        - name: PRODUCT_CATALOG_ADDR
          value: {{ quote .Values.opentelemetryDemoRecommendationservice.recommendationservice.env.productCatalogServiceAddr
            }}
        - name: OTEL_PYTHON_LOG_CORRELATION
          value: {{ quote .Values.opentelemetryDemoRecommendationservice.recommendationservice.env.otelPythonLogCorrelation
            }}
        - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
          value: {{ quote .Values.opentelemetryDemoRecommendationservice.recommendationservice.env.protocolBuffersPythonImplementation
            }}
        - name: FLAGD_HOST
          value: {{ quote .Values.opentelemetryDemoRecommendationservice.recommendationservice.env.flagdHost
            }}
        - name: FLAGD_PORT
          value: {{ quote .Values.opentelemetryDemoRecommendationservice.recommendationservice.env.flagdPort
            }}
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ quote .Values.opentelemetryDemoRecommendationservice.recommendationservice.env.otelExporterOtlpEndpoint
            }}
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: {{ quote .Values.opentelemetryDemoRecommendationservice.recommendationservice.env.otelResourceAttributes
            }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: '{{ .Values.opentelemetryDemoRecommendationservice.recommendationservice.image.repository
          }}:{{ .Values.opentelemetryDemoRecommendationservice.recommendationservice.image.tag
          | default .Chart.AppVersion }}'
        imagePullPolicy: {{ .Values.opentelemetryDemoRecommendationservice.recommendationservice.imagePullPolicy
          }}
        name: recommendationservice
        ports:
        - containerPort: 8080
          name: service
        resources: {{- toYaml .Values.opentelemetryDemoRecommendationservice.recommendationservice.resources
          | nindent 10 }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
