apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namespace }}-{{ include "recommendation.fullname" . }}
  labels:
    app.kubernetes.io/component: recommendationservice
    app.kubernetes.io/part-of: opentelemetry-demo
    opentelemetry.io/name: {{ .Values.namespace }}-{{ include "recommendation.fullname" . }}
  {{- include "recommendation.labels" . | nindent 4 }}
spec:
  type: {{ .Values.opentelemetryDemoRecommendationservice.type }}
  selector:
    opentelemetry.io/name: {{ .Values.namespace }}-{{ include "recommendation.fullname" . }}
    {{- include "recommendation.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.opentelemetryDemoRecommendationservice.ports | toYaml | nindent 2 }}
