namespace: opentelemetry-demo
kubernetesClusterDomain: cluster.local

serviceAccount:
  name: opentelemetry-demo
  version: ">=1.32.0-0"
  partOf: opentelemetry-demo

opentelemetryDemoLoadgenerator:
  loadgenerator:
    env:
      flagdHost: opentelemetry-demo-flagd
      flagdPort: "8013"
      locustAutostart: "true"
      locustBrowserTrafficEnabled: "true"
      locustHeadless: "false"
      locustHost: http://opentelemetry-demo-frontendproxy:8080
      locustSpawnRate: "1"
      locustUsers: "10"
      locustWebPort: "8089"
      otelCollectorName: opentelemetry-demo-otelcol
      otelExporterOtlpEndpoint: http://$(OTEL_COLLECTOR_NAME):4317
      otelExporterOtlpMetricsTemporalityPreference: cumulative
      otelResourceAttributes: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=2.1.3
      protocolBuffersPythonImplementation: python
    image:
      repository: ghcr.io/open-telemetry/demo
      tag: 2.1.3-load-generator
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 1500Mi
  ports:
  - name: tcp-service
    port: 8089
    targetPort: 8089
  replicas: 1
  revisionHistoryLimit: 10
  type: ClusterIP
