namespace: opentelemetry-demo
kubernetesClusterDomain: cluster.local

serviceAccount:
  name: opentelemetry-demo
  version: ">=1.32.0-0"
  partOf: opentelemetry-demo

opentelemetryDemoEmailservice:
  emailservice:
    env:
      appEnv: production
      emailServicePort: "8080"
      otelCollectorName: opentelemetry-demo-otelcol
      otelExporterOtlpMetricsTemporalityPreference: cumulative
      otelExporterOtlpTracesEndpoint: http://$(OTEL_COLLECTOR_NAME):4318/v1/traces
      otelResourceAttributes: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=2.1.3
    image:
      repository: ghcr.io/open-telemetry/demo
      tag: 2.1.3-email
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 100Mi
  ports:
  - name: tcp-service
    port: 8080
    targetPort: 8080
  replicas: 1
  revisionHistoryLimit: 10
  type: ClusterIP
