apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "frontend.fullname" . }}
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: opentelemetry-demo
    opentelemetry.io/name: {{ .Values.namespace }}-{{ include "frontend.fullname" . }}
  {{- include "frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.opentelemetryDemoFrontend.replicas }}
  revisionHistoryLimit: {{ .Values.opentelemetryDemoFrontend.revisionHistoryLimit }}
  selector:
    matchLabels:
      opentelemetry.io/name: {{ .Values.namespace }}-{{ include "frontend.fullname" . }}
    {{- include "frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: frontend
        app.kubernetes.io/instance: opentelemetry-demo
        app.kubernetes.io/name: {{ .Values.namespace }}-{{ include "frontend.fullname" . }}
        opentelemetry.io/name: {{ .Values.namespace }}-{{ include "frontend.fullname" . }}
      {{- include "frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/component']
        - name: OTEL_COLLECTOR_NAME
          value: {{ quote .Values.opentelemetryDemoFrontend.frontend.env.otelCollectorName }}
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: {{ quote .Values.opentelemetryDemoFrontend.frontend.env.otelExporterOtlpMetricsTemporalityPreference }}
        - name: FRONTEND_PORT
          value: {{ quote .Values.opentelemetryDemoFrontend.frontend.env.frontendPort }}
        - name: FRONTEND_ADDR
          value: {{ quote .Values.opentelemetryDemoFrontend.frontend.env.frontendAddr }}
        - name: AD_ADDR
          value: {{ quote .Values.opentelemetryDemoFrontend.frontend.env.adServiceAddr }}
        - name: CART_ADDR
          value: {{ quote .Values.opentelemetryDemoFrontend.frontend.env.cartServiceAddr }}
        - name: CHECKOUT_ADDR
          value: {{ quote .Values.opentelemetryDemoFrontend.frontend.env.checkoutServiceAddr }}
        - name: CURRENCY_ADDR
          value: {{ quote .Values.opentelemetryDemoFrontend.frontend.env.currencyServiceAddr }}
        - name: PRODUCT_CATALOG_ADDR
          value: {{ quote .Values.opentelemetryDemoFrontend.frontend.env.productCatalogServiceAddr }}
        - name: RECOMMENDATION_ADDR
          value: {{ quote .Values.opentelemetryDemoFrontend.frontend.env.recommendationServiceAddr }}
        - name: SHIPPING_ADDR
          value: {{ quote .Values.opentelemetryDemoFrontend.frontend.env.shippingServiceAddr }}
        - name: FLAGD_HOST
          value: {{ quote .Values.opentelemetryDemoFrontend.frontend.env.flagdHost }}
        - name: FLAGD_PORT
          value: {{ quote .Values.opentelemetryDemoFrontend.frontend.env.flagdPort }}
        - name: OTEL_COLLECTOR_HOST
          value: {{ quote .Values.opentelemetryDemoFrontend.frontend.env.otelCollectorHost }}
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ quote .Values.opentelemetryDemoFrontend.frontend.env.otelExporterOtlpEndpoint }}
        - name: WEB_OTEL_SERVICE_NAME
          value: {{ quote .Values.opentelemetryDemoFrontend.frontend.env.webOtelServiceName }}
        - name: PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: {{ quote .Values.opentelemetryDemoFrontend.frontend.env.publicOtelExporterOtlpTracesEndpoint }}
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: {{ quote .Values.opentelemetryDemoFrontend.frontend.env.otelResourceAttributes }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.opentelemetryDemoFrontend.frontend.image.repository }}:{{ .Values.opentelemetryDemoFrontend.frontend.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.opentelemetryDemoFrontend.frontend.imagePullPolicy }}
        name: frontend
        ports:
        - containerPort: 8080
          name: service
        resources: {{- toYaml .Values.opentelemetryDemoFrontend.frontend.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.opentelemetryDemoFrontend.frontend.containerSecurityContext | nindent 10 }}
      serviceAccountName: {{ .Values.serviceAccount.name }}