apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "payment.fullname" . }}
  labels:
    app.kubernetes.io/component: paymentservice
    app.kubernetes.io/part-of: opentelemetry-demo
    opentelemetry.io/name: {{ .Values.namespace }}-{{ include "payment.fullname" . }}
  {{- include "payment.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.opentelemetryDemoPaymentservice.replicas }}
  revisionHistoryLimit: {{ .Values.opentelemetryDemoPaymentservice.revisionHistoryLimit
    }}
  selector:
    matchLabels:
      opentelemetry.io/name: {{ .Values.namespace }}-{{ include "payment.fullname" . }}
    {{- include "payment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: paymentservice
        app.kubernetes.io/instance: opentelemetry-demo
        app.kubernetes.io/name: {{ .Values.namespace }}-{{ include "payment.fullname" . }}
        opentelemetry.io/name: {{ .Values.namespace }}-{{ include "payment.fullname" . }}
      {{- include "payment.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/component']
        - name: OTEL_COLLECTOR_NAME
          value: {{ quote .Values.opentelemetryDemoPaymentservice.paymentservice.env.otelCollectorName
            }}
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: {{ quote .Values.opentelemetryDemoPaymentservice.paymentservice.env.otelExporterOtlpMetricsTemporalityPreference
            }}
        - name: PAYMENT_PORT
          value: {{ quote .Values.opentelemetryDemoPaymentservice.paymentservice.env.paymentServicePort
            }}
        - name: FLAGD_HOST
          value: {{ quote .Values.opentelemetryDemoPaymentservice.paymentservice.env.flagdHost
            }}
        - name: FLAGD_PORT
          value: {{ quote .Values.opentelemetryDemoPaymentservice.paymentservice.env.flagdPort
            }}
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ quote .Values.opentelemetryDemoPaymentservice.paymentservice.env.otelExporterOtlpEndpoint
            }}
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: {{ quote .Values.opentelemetryDemoPaymentservice.paymentservice.env.otelResourceAttributes
            }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: '{{ .Values.opentelemetryDemoPaymentservice.paymentservice.image.repository
          }}:{{ .Values.opentelemetryDemoPaymentservice.paymentservice.image.tag | default
          .Chart.AppVersion }}'
        imagePullPolicy: {{ .Values.opentelemetryDemoPaymentservice.paymentservice.imagePullPolicy
          }}
        name: paymentservice
        ports:
        - containerPort: 8080
          name: service
        resources: {{- toYaml .Values.opentelemetryDemoPaymentservice.paymentservice.resources
          | nindent 10 }}
        securityContext: {{- toYaml .Values.opentelemetryDemoPaymentservice.paymentservice.containerSecurityContext
          | nindent 10 }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
