apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namespace }}-{{ include "payment.fullname" . }}
  labels:
    app.kubernetes.io/component: paymentservice
    app.kubernetes.io/part-of: opentelemetry-demo
    opentelemetry.io/name: {{ .Values.namespace }}-{{ include "payment.fullname" . }}
  {{- include "payment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.opentelemetryDemoPaymentservice.type }}
  selector:
    opentelemetry.io/name: {{ .Values.namespace }}-{{ include "payment.fullname" . }}
    {{- include "payment.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.opentelemetryDemoPaymentservice.ports | toYaml | nindent 2 }}
