apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "ad.fullname" . }}
  labels:
    app.kubernetes.io/component: adservice
    app.kubernetes.io/part-of: opentelemetry-demo
    opentelemetry.io/name: {{ .Values.namespace }}-{{ include "ad.fullname" . }}  # Changed this line
  {{- include "ad.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.opentelemetryDemoAdservice.replicas }}
  revisionHistoryLimit: {{ .Values.opentelemetryDemoAdservice.revisionHistoryLimit }}
  selector:
    matchLabels:
      opentelemetry.io/name: {{ .Values.namespace }}-{{ include "ad.fullname" . }}  # Changed this line
    {{- include "ad.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: adservice
        app.kubernetes.io/instance: opentelemetry-demo
        app.kubernetes.io/name: {{ .Values.namespace }}-{{ include "ad.fullname" . }}  # Changed this line
        opentelemetry.io/name: {{ .Values.namespace }}-{{ include "ad.fullname" . }}  # Changed this line
      {{- include "ad.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/component']
        - name: OTEL_COLLECTOR_NAME
          value: {{ quote .Values.opentelemetryDemoAdservice.adservice.env.otelCollectorName }}
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: {{ quote .Values.opentelemetryDemoAdservice.adservice.env.otelExporterOtlpMetricsTemporalityPreference }}
        - name: AD_PORT
          value: {{ quote .Values.opentelemetryDemoAdservice.adservice.env.adServicePort }}
        - name: FLAGD_HOST
          value: {{ quote .Values.opentelemetryDemoAdservice.adservice.env.flagdHost }}
        - name: FLAGD_PORT
          value: {{ quote .Values.opentelemetryDemoAdservice.adservice.env.flagdPort }}
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ quote .Values.opentelemetryDemoAdservice.adservice.env.otelExporterOtlpEndpoint }}
        - name: OTEL_LOGS_EXPORTER
          value: {{ quote .Values.opentelemetryDemoAdservice.adservice.env.otelLogsExporter }}
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: {{ quote .Values.opentelemetryDemoAdservice.adservice.env.otelResourceAttributes }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.opentelemetryDemoAdservice.adservice.image.repository }}:{{ .Values.opentelemetryDemoAdservice.adservice.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.opentelemetryDemoAdservice.adservice.imagePullPolicy }}
        name: adservice
        ports:
        - containerPort: 8080
          name: service
        resources: {{- toYaml .Values.opentelemetryDemoAdservice.adservice.resources | nindent 10 }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
