namespace: opentelemetry-demo
kubernetesClusterDomain: cluster.local

serviceAccount:
  name: opentelemetry-demo
  version: ">=1.32.0-0"
  partOf: opentelemetry-demo

opentelemetryDemoPaymentservice:
  paymentservice:
    containerSecurityContext:
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    env:
      flagdHost: opentelemetry-demo-flagd
      flagdPort: "8013"
      otelCollectorName: opentelemetry-demo-otelcol
      otelExporterOtlpEndpoint: http://$(OTEL_COLLECTOR_NAME):4317
      otelExporterOtlpMetricsTemporalityPreference: cumulative
      otelResourceAttributes: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=2.1.3
      paymentServicePort: "8080"
    image:
      repository: ghcr.io/open-telemetry/demo
      tag: 2.1.3-payment
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 120Mi
  ports:
  - name: tcp-service
    port: 8080
    targetPort: 8080
  replicas: 1
  revisionHistoryLimit: 10
  type: ClusterIP
