apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namespace }}-{{ include "kafka.fullname" . }}
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/part-of: opentelemetry-demo
    opentelemetry.io/name: {{ .Values.namespace }}-{{ include "kafka.fullname" . }}
  {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.opentelemetryDemoKafka.type }}
  selector:
    opentelemetry.io/name: {{ .Values.namespace }}-{{ include "kafka.fullname" . }}
    {{- include "kafka.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.opentelemetryDemoKafka.ports | toYaml | nindent 2 }}
