apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "imageprovider.fullname" . }}
  labels:
    app.kubernetes.io/component: imageprovider
    app.kubernetes.io/part-of: opentelemetry-demo
    opentelemetry.io/name: {{ .Values.namespace }}-{{ include "imageprovider.fullname" . }}
  {{- include "imageprovider.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.opentelemetryDemoImageprovider.replicas }}
  revisionHistoryLimit: {{ .Values.opentelemetryDemoImageprovider.revisionHistoryLimit
    }}
  selector:
    matchLabels:
      opentelemetry.io/name: {{ .Values.namespace }}-{{ include "imageprovider.fullname" . }}
    {{- include "imageprovider.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: imageprovider
        app.kubernetes.io/instance: opentelemetry-demo
        app.kubernetes.io/name: {{ .Values.namespace }}-{{ include "imageprovider.fullname" . }}
        opentelemetry.io/name: {{ .Values.namespace }}-{{ include "imageprovider.fullname" . }}
      {{- include "imageprovider.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/component']
        - name: OTEL_COLLECTOR_NAME
          value: {{ quote .Values.opentelemetryDemoImageprovider.imageprovider.env.otelCollectorName
            }}
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: {{ quote .Values.opentelemetryDemoImageprovider.imageprovider.env.otelExporterOtlpMetricsTemporalityPreference
            }}
        - name: IMAGE_PROVIDER_PORT
          value: {{ quote .Values.opentelemetryDemoImageprovider.imageprovider.env.imageProviderPort
            }}
        - name: OTEL_COLLECTOR_PORT_GRPC
          value: {{ quote .Values.opentelemetryDemoImageprovider.imageprovider.env.otelCollectorPortGrpc
            }}
        - name: OTEL_COLLECTOR_HOST
          value: {{ quote .Values.opentelemetryDemoImageprovider.imageprovider.env.otelCollectorHost
            }}
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: {{ quote .Values.opentelemetryDemoImageprovider.imageprovider.env.otelResourceAttributes
            }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: '{{ .Values.opentelemetryDemoImageprovider.imageprovider.image.repository
          }}:{{ .Values.opentelemetryDemoImageprovider.imageprovider.image.tag | default
          .Chart.AppVersion }}'
        imagePullPolicy: {{ .Values.opentelemetryDemoImageprovider.imageprovider.imagePullPolicy
          }}
        name: imageprovider
        ports:
        - containerPort: 8081
          name: service
        resources: {{- toYaml .Values.opentelemetryDemoImageprovider.imageprovider.resources
          | nindent 10 }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
