namespace: opentelemetry-demo
kubernetesClusterDomain: cluster.local

serviceAccount:
  name: opentelemetry-demo
  version: ">=1.32.0-0"
  partOf: opentelemetry-demo

opentelemetryDemoQuoteservice:
  ports:
  - name: tcp-service
    port: 8080
    targetPort: 8080
  quoteservice:
    containerSecurityContext:
      runAsGroup: 33
      runAsNonRoot: true
      runAsUser: 33
    env:
      otelCollectorName: opentelemetry-demo-otelcol
      otelExporterOtlpEndpoint: http://$(OTEL_COLLECTOR_NAME):4318
      otelExporterOtlpMetricsTemporalityPreference: cumulative
      otelPhpAutoloadEnabled: "true"
      otelResourceAttributes: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=2.1.3
      quoteServicePort: "8080"
    image:
      repository: ghcr.io/open-telemetry/demo
      tag: 2.1.3-quote
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 40Mi
  replicas: 1
  revisionHistoryLimit: 10
  type: ClusterIP
