apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namespace }}-{{ include "quote.fullname" . }}
  labels:
    app.kubernetes.io/component: quoteservice
    app.kubernetes.io/part-of: opentelemetry-demo
    opentelemetry.io/name: {{ .Values.namespace }}-{{ include "quote.fullname" . }}
  {{- include "quote.labels" . | nindent 4 }}
spec:
  type: {{ .Values.opentelemetryDemoQuoteservice.type }}
  selector:
    opentelemetry.io/name: {{ .Values.namespace }}-{{ include "quote.fullname" . }}
    {{- include "quote.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.opentelemetryDemoQuoteservice.ports | toYaml | nindent 2 }}
